# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kxq82ZsguSaXyiAGQgnKFS_hi9GgnmRJ
"""

#ex
class Point3:
  def __init__(self, x, y, z):
    self.x = x
    self.y = y
    self.z = z
  def translate(self, dx, dy, dz):
    self.x += dx
    self.y += dy
    self.z += dz
  def __str__(self):
    return f"({str(self.x)}, {str(self.y)}, {self.z})"
p = Point3(1,2,3)
p.translate(10, 0, -1)

class Account:
    def __init__(self, owner, number):
        self._owner = owner
        self._number = number
        self._balance = 0.0

    def deposit(self, amount):
        self._balance += amount

    def withdraw(self, amount):
        self._balance -= amount

    def balance(self):
        return self._balance
class FeeAccount(Account):
  def __init__(self, owner, number, fee):
    super().__init__(owner, number)
    self._fee = fee
  def withdraw(self, amount):
    super().withdraw(amount + self.fee)

#1
class Cylinder():
  def __init__(self, radius, height):
    self.radius = radius
    self.height = height
  def total_area(self):
    return round(2*3.14*self.radius*self.height + 3.14*self.radius**2, 2)
  def volume(self):
    return round(3.14*self.radius*self.radius*self.height, 2)

hinh = Cylinder(3,4)
print(hinh.total_area())
print(hinh.volume())

#2
class Date():
  def __init__(self, day, month, year):
    self.day = day
    self.month = month
    self.year = year
  def checl(self):
    if 0 < self.day <= 31 and 0 < self.month <= 12 and self.year > 0:
      if self.month == 2:
        if self.year % 400 == 0:
          if self.day == 29:
            self.day = 1
            self.month += 1
            print(f"{self.day}/{self.month}/{self.year}")

      if self.month == 4 or self.month == 6 or self.month == 9 or self.month ==11:
        if self.day > 30:
          return "INVALID"
        elif self.day == 30:
          self.day = 1
          self.month += 1
          print(f"{self.day}/{self.month}/{self.year}")
      if self.month == 1 or self.month == 3 or self.month == 5 or self.month == 7 or self.month == 8 or self.month == 10 or self.month == 12:
        if self.day > 31:
          return "INVALID"
        if self.day == 31:
          if self.month == 12:
            self.day = 1
            self.month = 1
            self.year += 1
            print(f"{self.day}/{self.month}/{self.year}")
          else:
            self.day = 1
            self.month += 1
            print(f"{self.day}/{self.month}/{self.year}")
    else:
      return "INVALID"

year = int(input())
def check(n):
  if n % 4 == 0:
    if n % 100 == 0:
      if n % 400 == 0:
        return "True"
      else:
        return "False"
    else:
      return "True"
  else:
    return "False"
check(year)

#3
class Point():
  def __init__(self, x, y):
    self.x = x
    self.y = y
  def distance(self):
    self.distance = (self.x**2 + self.y**2)**0.5
  def check(self):
    if self.x == self.y == 0:
      return "M la goc toa do"
    elif self.x == 0:
      return "M nam tren truc hoanh"
    elif self.y == 0:
      return "M nam tren truc tung"
    else:
      return f"Khoang cach tu M toi goc toa do{self.distance}"
point1 = Point(0, 0)
point1.distance()
point1.check()

#4
class Caculator():
  def __init__(self, a, b):
    self.a = a
    self.b = b
  def add(self):
    return self.a + self.b
  def subtract(self):
    return self.a - self.b
  def product(self):
    return self.a * self.b
  def divide(self):
    if self.b == 0:
      return "INVAID"
    return self.a / self.b
  def power(self):
    return self.a**self.b
  def mod(self):
    if self.b == 0:
      return "INVAID"
    return self.a % self.b
  def set_numbers(self, a, b):
    self.a = a
    self.b = b
a, b = map(int, input("Nhap 2 so").split())
so = Caculator(a, b)
while True:
  print("Your choice")
  print("1. Add / 2. Subtract/ 3. Product/ 4. Divide/ 5. Power/ 6. Mod/ 7. Set numbers")
  choice = int(input("Your choice"))
  if choice == 1:
    print(f"Add:{so.add()}")
  elif choice == 2:
    print(f"Subtract:{so.subtract()}")
  elif choice == 3:
    print(f"Product:{so.product()}")
  elif choice == 4:
    print(f"Divide:{so.divide()}")
  elif choice == 5:
    print(f"Power:{so.power()}")
  elif choice == 6:
    print(f"Mod:{so.mod()}")
  elif choice == 7:
    a, b = map(int, input("Nhap lai 2 so").split())
    so.set_numbers(a, b)
  end = input("Ban co muon thoat")
  if end == "yes" or end == "Yes" or end == "YES":
    break

#5
class ShoppingCart():
  def __init__(self):
    self.items = []
  def add(self, name, price):
    product = {name:price}
    self.items.append(product)
  def remove(self, name):
    for item in self.items:
      if name in item:
        self.items.remove(item)
        return True
  def check(self):
    if self.items == []:
      return "Gio hang rong"
    return "Gio hang khong rong"
  def total(self):
    total = 0
    for item in self.items:
      for value in item.values():
        total += value
    return total
  def display(self):
    return f"Toan bo gio hang{self.items}"
  def clear(self):
    self.items = []
so = ShoppingCart()
while True:
  print("2. Add\n3. Remove\n4. Check\n5. Total\n6. Display\n7. Clear")
  print("Your choice")
  choice = int(input())
  if choice == 2:
    name = input("Nhap ten san pham")
    price = int(input("Nhap gia san pham"))
    so.add(name, price)
  if choice == 3:
    name = input("Nhap ten san pham can xoa")
    if so.remove(name):
      print("Da xoa san pham")
    else:
      print("Khong tim thay san pham")
  if choice == 4:
    print(so.check())
  if choice == 5:
    print(so.total())
  if choice == 6:
    print(so.display())
  if choice == 7:
    so.clear()
  stop = input("Ban co muon thoat khoi chuong trinh khong")
  if stop == "yes" or stop == "Yes" or stop == "YES":
    break

dict = {"name":price}
print(dict["name"])

#6
class Rectangle():
  def __init__(self, width, length):
    self.width = width
    self.length = length
  def area(self):
    return f"{(self.width * self.length):.2f}"
  def perimeter(self):
    return f"{((self.width + self.length) * 2):.2f}"
  def scale(self, k):
    self.width *= k
    self.length *= k
hinh1 = Rectangle(2, 5)
hinh1.scale(2)
print(hinh1.area())
print(hinh1.perimeter())

#7
def check(m, n):
  if int(m) == m and int(n) == n and n != 0:
    return True
  else:
    return False
import math
class Fraction():
  def __init__(self, num, den):
    self.num = num//math.gcd(num, den)
    self.den = den//math.gcd(num, den)
    if self.den < 0:
      self.num *= -1
      self.den *= -1
  def __str__(self):
    return f"{self.num}/{self.den}"
  def add(self, other):
    return Fraction(self.num*other.den + self.den*other.num, self.den*other.den)
  def sub(self, other):
    return Fraction(self.num*other.den - self.den*other.num, self.den*other.den)
  def mul(self, other):
    return Fraction(self.num*other.num, self.den*other.den)
  def div(self, other):
    return Fraction(self.num*other.den, self.den*other.num)
a, b, op, c, d = input().split()
so1 = Fraction(int(a), int(b))
so2 = Fraction(int(c), int(d))
if op == "+":
  print(so1.add(so2))
if op == "-":
  print(so1.sub(so2))
if op == "*":
  print(so1.mul(so2))
if op == "/":
  print(so1.div(so2))

#9
class Student():
  def __init__(self, name):
    self.name = name
    self.scores = []
  def add_score(self, subject, score):
    self.subject = subject
    self.score = score
    self.scores.append((subject, score))
  def avg(self):
    avg = 0
    for score in self.scores:
      avg = avg + score[1]
    return avg/len(self.scores)
  def rank(self,student):
    if student.avg() >= 8:
      print(student.avg())
      return "Excellent"
    elif  6.5 < student.avg() < 8:
      return "Good"
    elif 5 < student.avg() <= 6.5:
      return "Average"
    else:
      return "Poor"
name = input("Nhap ten hoc sinh")
hs = Student(name)
n = int(input())
for i in range(n):
  subject = input("Nhap mon hoc")
  score = int(input("Nhap diem"))
  hs.add_score(subject, score)
print(f"{name}{hs.avg()}{hs.rank(hs)}")

#10
class Book():
  def __init__(self, tittle, author, year):
    self.tittle = tittle
    self.author = author
    self.year = year
class Library():
  def __init__(self):
    self.lib = []
  def add(self, book):
    self.lib.append(book)
  def count_by_author(self, name):
    count = 0
    for i in self.lib:
      if i.author == name:
        count += 1
    return count
  def find_by_year(self, year):
    count = 0
    for i in self.lib:
      if i.year == year:
        count += 1
    return count
Lib = Library()
n = int(input())
for i in range(n):
  s = list(input().split())
  book = Book(s[1], s[2], s[3])
  Lib.add(book)
  if i == n - 1:
    s1, s2 = map(str, input().split())
    if s1 == "COUNT":
      print(Lib.count_by_author(s2))
    elif s1 == "COUNTYEAR":
      print(Lib.find_by_year(s2))

#11
import math
class toado():
  def __init__(self, x, y, z):
    self.x = x
    self.y = y
    self.z = z
  def vecto(self, other):
    x = self.x - other.x
    y = self.y - other.y
    z = self.z - other.z
    result = toado(x, y, z)
    return result
  def phaptuyen(self, other):
    x = self.y*other.z - self.z*other.y
    y = self.z*other.x - self.x*other.z
    z = self.x*other.y - self.y*other.x
    result = toado(x, y, z)
    return result
  def length(self):
    return math.sqrt(self.x**2 + self.y**2 + self.z**2)
  def __str__(self):
    return f"{self.x} {self.y} {self.z}"
x, y, z = map(float, input().split())
A = toado(x, y, z)

x, y, z = map(float, input().split())
B = toado(x, y, z)

x, y, z = map(float, input().split())
C = toado(x, y, z)

x, y, z = map(float, input().split())
D = toado(x, y, z)

v1 = A.vecto(B)
v2 = A.vecto(C)
v3 = B.vecto(C)
v4 = B.vecto(D)

v5 = v1.phaptuyen(v2)
v6 = v3.phaptuyen(v4)

goc = (v5.x * v6.x + v5.y * v6.y + v5.z * v6.z) / (v5.length() * v6.length())
goc = math.acos(goc)
goc = math.degrees(goc)
print(f"{goc:.2f}")

#12
class ComplexNumber():
  def __init__(self, a, b):
    self.RealPart = a
    self.imaginaryPart = b
  def ComplexNumber_multiply(self, other):
    return f"{self.RealPart*other.RealPart - self.imaginaryPart*other.imaginaryPart} {self.RealPart*other.imaginaryPart+self.imaginaryPart*other.RealPart}"
so1 = ComplexNumber(2,3)
so2 = ComplexNumber(3,2)
so1.ComplexNumber_multiply(so2)

#13
def checkduong(x, y ,z):
  if x > 0 and y > 0 and z > 0:
    return True
  return False
def checktamgiac(x, y ,z):
  if x+y > z and x+z > y and y+z > x:
    return True
  return False
import math
class Triangle():
  def __init__(self, egde1, egde2, egde3):
    self.egde1 = egde1
    self.egde2 = egde2
    self.egde3 = egde3
  def getArea(self):
    if checkduong(self.egde1, self.egde2, self.egde3):
      if checktamgiac(self.egde1, self.egde2, self.egde3):
        p = (self.egde1 + self.egde2 + self.egde3)/2
        S = math.sqrt((p*(p - self.egde1)*(p - self.egde2)*(p - self.egde3)))
        return f"Dien tich{S:.2f}"
      else:
        return "Invalid"
a, b, c = map(int, input().split())
tamgiac1 = Triangle(a, b, c)
tamgiac1.getArea()