# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18EH-rbcG9RTeFolR4c2DntiklYpV9Z-q
"""

#1
chuoi = input().split()
count = 0
lst = []
for i in chuoi:
  if count != i:
    count = i
    lst.append(i)
print(lst)

#2
chuoi = map(int, input().split())
lst = []
tong = 0
for i in chuoi:
  tong += i
  lst.append(tong)
print(lst)

#3
numbers = tuple(map(int, input("Nhap day").split()))
k = int(input())
k = k % len(numbers)
result = numbers[k:] + numbers[:k]
print(result)

#4
n = input().split()
dic = {}
for i in n:
  k, v = i.split(":")
  if k not in dic:
    dic[k] = [v]
  else:
    dic[k].append(v)
print(dic)

#5
n = list(map(int, input().split()))
result = {
    "positive" : sum(1 for i in n if i > 0),
    "negative" : sum(1 for i in n if i < 0),
    "zero" : sum(1 for i in n if i == 0),
}
print(result)

#6
numbers = list(map, int(input("Nhap day").split()))
tong = 0
for i in numbers:
  tong += i
print(tong)

#6
tong = 0
n = list(map(int, input().split()))
for i in n:
  tong += i
print(tong)

#7
tple = tuple(input().split())
lst = list(tple)
lst = lst[::-1]
print(tple[0],tple[len(tple)-1])
print(tuple(lst))

#8
n = list(input().split())
dic = {}
for i in n:
  if i not in dic:
    dic[i] = 1
  else:
    dic[i] +=1
print(dic)

#9
def dic(n):
  dic = {}
  for i in n:
    k , v = i.split(":")
    if i not in dic:
      dic[k] = v
  return dic
dic1 = list(input().split())
dic2 = list(input().split())
new_dict = {}
for i in dic(dic1).keys():
  for j in dic(dic2).keys():
    if i == j:
      new_dict[i] = int(dic(dic1)[i]) + int(dic(dic2)[j])
print(new_dict)

#10
lst = list(map(int, input().split()))
k = int(input())
result = set()
for i in range(len(lst)):
  for j in range(i+1, len(lst)):
    if lst[i] + lst[j] == k:
      result.add((lst[i], lst[j]))
result1 = sorted(result)
print(result1)

#11
day = tuple(map(int, input().split()))
sochan = ()
sole = ()
for i in day:
  if i % 2 == 0:
    sochan += (i,)
  else:
    sole += (i,)
print(sochan)
print(sole)

#12
n = input().split()
dic = {}
for i in n:
  k, v = i.split(" ")
  if k not in dic:
    dic[k] = v
  for i in dic:

#13
n = list(map(str, input().split()))
dict = {}
for i in range(1, len(n), 2):
  dict[n[i]] = n[i-1]
print(dict)

#14
day1 = list(map(int, input().split()))
day2 = list(map(int, input().split()))
lst = []
for i in day1:
  for j in day2:
    if i == j:
      if i not in lst:
        lst.append(i)
print(lst)

#15
dict = list(input().split())
k = int(input())
new_dict = {}
for i in range(1, len(dict), 2):
  if int(dict[i]) > k:
    new_dict[dict[i-1]] = dict[i]
print(new_dict)

#17
n = int(input("Nhap so hang"))
ma_tran = []
for i in range(n):
  row = []
  for j in range(n):
    a = int(input())
    row.append(a)
  ma_tran.append(row)
for row in ma_tran:
  for i in row:
    print(f"{i:4d}", end="")
  print()
for i in range(n):
  for j in range(n):
    if i == j:
      print(ma_tran[i][j], end=" ")

#16
n = int(input("Nhap so hang"))
m = int(innp("Nhap so cot"))
ma_tran = []
for i in range(n):
  row = []
  for j in range(m):
    a = int(input())
    row.append(a)
  ma_tran.append(row)
for row in ma_tran:
  for i in row:
    print(f"{item:4d}", end="")

#18
n, m, k= map(int, input("Nhap so hang cot k").split())
ma_tran = []
for i in range(n):
  row = []
  for j in range(m):
    a = int(input())
    row.append(a)
  ma_tran.append(row)
tong = 0
for i in range(n):
  tong += ma_tran[i][k-1]
print(tong)

#19
lst = list(map(int, input().split()))
so_max = 0
for i in lst:
  if i > so_max:
    so_max = i
print(so_max)

#20
def check(m, n):
  for i in range(len(m)- 1):
    if m[i] == n:
      return i+1
    else:
      return -1
lst = list(map(int, input().split()))
k = int(input())
check(lst, k)

#21
lst = input().split()
dict = {}
for i in range(len(lst)- 1):
  if lst[i] not in dict:
    dict[lst[i]] = (i,)
  else:
    dict[lst[i]] += (i,)
print(dict)