# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BaGqotyJRoEPQsrzFQTWLCpuALa_BBIq
"""

#9A1
def merge(lst1, lst2):
 i, j = 0, 0
 result = []
 while i < len(lst1) and j < len(lst2):
  if lst1[i] <= lst2[j]:
   result.append(lst1[i])
   i += 1
  else:
   result.append(lst2[j])
   j += 1
 result.extend(lst1[i:])
 result.extend(lst2[j:])
 return result
lst1 = [1, 2, 3, 4, 5]
lst2 = [2, 3, 4, 5, 6, 7, 8, 9]
print(merge(lst1, lst2))

#9A2
n = int(input())
m = int(input())
k = int(input())
lst = []
for i in range(n):
 row = list(map(int, input().split()))
 lst.append(row)
lst1 = []
for i in lst:
  for j in i:
    lst1.append(j)
lst1.sort()
print(lst1[k-1])

#9A3
def findmin(n):
 s = list(str(n))
 min = n
 for i in range(len(s)):
  for j in range(i+1, len(s)):
   s[i], s[j] = s[j], s[i]
   if s[0] != '0':
    a = int("".join(s))
    min = min(min, a)
  s[i], s[j] = s[j], s[i]
 return min
print(findmin(12345))

#9A4
Q = int(input())
for _ in range(Q):
  a = input()
  b = input()
  idx = 0
  result = False
  for i in range(len(a)):
    chu1 = a[i].lower()
    chu2 = b[id].lower()
    if chu1 == chu2:
      idx += 1
    if idx == len(b):
      result = True
if result:
  print("Yes")
else:
  print("No")

#9A5
def check(list1, list2):
 m = len(list1)
 n = len(list2)
 if m > n:
  return False
 for i in range(n - m + 1):
  if list2[i:i+m] == list1:
   return True
 return False

#9A6
def hoanvitieptheo(a):
 n = len(a)
 i = n - 2
 while i >= 0 and a[i] >= a[i + 1]:
  i -= 1
 if i >= 0:
  j = n - 1
  while a[j] <= a[i]:
   j -= 1
  a[i], a[j] = a[j], a[i]
 a[i + 1:] = reversed(a[i + 1:])
 return a
n = int(input())
a = list(map(int, input().split()))
next = hoanvitieptheo(a)
print(*next)

#9A7
def canPlaceFlowers(flowerbed, k):
 n = len(flowerbed)
 i = 0
 while i < n:
  if (flowerbed[i] == 0 and (i == 0 or flowerbed[i-1] == 0) and (i == n-1 or flowerbed[i+1] == 0)):
    flowerbed[i] = 1
    k -= 1
    if k == 0:
      return True
    i += 2
  else:
   i += 1
 return k <= 0
flowerbed = [1,0,0,0,1]
k = 1
print(canPlaceFlowers(flowerbed, k))

#9A8
def is_path_crossing(moves):
  x, y = 0, 0
  toado = set()
  toado.add((x, y))
  for move in moves:
    if move == 'R':
      x += 1
      if (x, y) in toado:
        return True
    elif move == 'L':
      x -= 1
      if (x, y) in toado:
        return True
    elif move == 'U':
      y += 1
      if (x, y) in toado:
        return True
    elif move == 'D':
      y -= 1
      if (x, y) in toado:
        return True
    toado.add((x, y))
  return False
print(is_path_crossing("RU"))

#9A9
def Median(nums):
 a, b, c, d, e = nums
 if a > b:
  a, b = b, a
 if c > d:
  c, d = d, c
 if a > c:
  a, c = c, a
  b, d = d, b
 if b > e:
  b, e = e, b
 if b > c:
  b, c = c, b
 if c > e:
  c, e = e, c
 return c
nums = [1, 10, 3, 8, 5]
print(Median(nums))

#9A10
def findRadius(houses, heaters):
 if not houses or not heaters:
  return 0
 houses.sort()
 heaters.sort()
 i = 0
 r = 0
 for house in houses:
  while i < len(heaters) - 1 and abs(heaters[i + 1] - house) <= abs(heaters[i] - house):
   i += 1
   r = max(r, abs(heaters[i] - house))
 return r
houses = [1, 2, 3]
heaters = [2]
print(findRadius(houses, heaters))