# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1goc0OyPYMOE-Jo4fvQhWWIGpiGhV4_aD
"""

#7A1
def binary_search(arr, value):
 left, right = 0, len(arr) - 1
 while left <= right:
  mid = (left + right) // 2
  if arr[mid] == value:
   return mid
  elif arr[mid] < value:
   left = mid + 1
  else:
   right = mid - 1
 return -1

arr = [1, 2, 3, 4, 5, 6]
value = 7
print(binary_search(arr, value))

#7A2
def count_occurrences(arr, x):
  count = 0
  for i in arr:
    if i == x:
      count += 1
  return count
arr = [1, 2, 3, 4, 5, 6, 2, 2]
x = 2
print(count_occurrences(arr,x))

#7A3
def bubble_sort(arr):
 n = len(arr)
 for i in range(n):
  swapped = False
  for j in range(0, n-i-1):
   if arr[j] > arr[j+1]:
    arr[j], arr[j+1] = arr[j+1], arr[j]
    swapped = True
  if not swapped:
   break
 return arr

def selection_sort(arr):
 n = len(arr)
 for i in range(n):
  min_idx = i
  for j in range(i+1, n):
   if arr[j] < arr[min_idx]:
    min_idx = j
  arr[i], arr[min_idx] = arr[min_idx], arr[i]
 return arr


arr = [3, 2, 4, 5, 7, 8, 6, 1, 2, 3]
print(bubble_sort(arr))
print(selection_sort(arr))

#7A4
def bubble_sort(arr):
 n = len(arr)
 for i in range(n):
  swapped = False
  for j in range(0, n-i-1):
   if arr[j] > arr[j+1]:
    arr[j], arr[j+1] = arr[j+1], arr[j]
    swapped = True
  if not swapped:
   break
 return arr
def sort(lst):
 if not lst:
  return None
 first_pos = {}
 for i, x in enumerate(lst):
  if x not in first_pos:
   first_pos[x] = i
 arr = lst[:]
 bubble_sort(arr)
 max_count = 1
 count = 1
 result = arr[0]
 for i in range(1, len(arr)):
  if arr[i] == arr[i - 1]:
   count += 1
  else:
   count = 1
  if count > max_count:
   max_count = count
   result = arr[i]
  elif count == max_count:
   if first_pos[arr[i]] < first_pos[result]:
    result = arr[i]
 return result

a = [2, 3, 4, 2, 2, 5]
print(sort(a))

#7A5
lst = list(map(int, input().split()))
x = int(input())
count = 0
for i in lst:
  for j in lst:
    if i+j == x:
      count += 1
print(count)

#7A6
s = input()
lst = eval(s)
result = []
for item in lst:
    for i in item:
        result.append(i)
print(result)

#7A7
def length(lst):
 n = len(lst)
 if n == 0:
  return 0
 dp = [1] * n
 for i in range(n):
  for j in range(i):
   if lst[j] < lst[i]:
    dp[i] = max(dp[i], dp[j] + 1)
 return max(dp)
lst = [0, 1, 0, 3, 2, 3]
print(length(lst))

#7A11
sentence = list(input().split(" "))
word = input()
count = 0
for i in sentence:
  if word == i:
    count += 1
print(count)

#7A12
lst = []
dapan = ['A', 'B', 'C', 'D']
vitri = 0
for _ in range(4):
  s = input()
  lst.append([s, vitri])
  vitri += 1
lst.sort()
for i in lst:
    print(dapan[i[1]], end=" ")

#7A14
n = int(input())
lst = list(map(int, input().split()))
result = []
for i in range(0, len(lst)):
 if lst[i] == 7:
  result.append(i)
if len(result) == 0:
  print("Not found")
else:
  result.sort(reverse=True)
  print(result)

#7A15
n = int(input())
lst = []
for _ in range(n):
  s = input()
  lst.append(s)
for i in range(len(lst)):
    if i == 0:
      print(lst[i+1], lst[-1])
    if i == len(lst) - 1:
      print(lst[i-1], lst[0])
    else:
      print(lst[i-1], lst[i + 1])